# Based on https://github.com/rusty1s/pytorch_scatter/blob/master/.github/workflows/building.yml

name: Building Fat Wheels

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Building Wheels"]
    types:
      - completed

jobs:

  wheel:
    runs-on: ${{ matrix.os }}
    # if: ${{ github.event.workflow_run.conclusion == 'success' }}
    permissions:
      actions: read
      contents: read

    strategy:
      fail-fast: false
      matrix:
        # os: [ubuntu-22.04, macos-14, windows-2022]
        os: [macos-14]

    steps:
      - uses: actions/checkout@v2

      - name: Grab library files
        uses: actions/download-artifact@v5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          # run-id: ${{ github.event.workflow_run.id }}
          run-id: 17470065659
          pattern: lib-${{ matrix.os }}*
          merge-multiple: true
          path: torbi/

      - name: List Files
        run: |
            ls torbi
            ls .

      # - name: Set up Python ${{ matrix.python-version }}
      #   uses: actions/setup-python@v2
      #   with:
      #     python-version: 3.9

      # - name: Upgrade pip
      #   run: |
      #     pip install --upgrade setuptools
      #     pip install wheel

      # - name: Free Disk Space (Ubuntu)
      #   if: ${{ runner.os == 'Linux' }}
      #   uses: jlumbroso/free-disk-space@main

      # - name: Install Build Deps
      #   run: |
      #     pip install build twine "setuptools<70" numpy torch



      # - name: Build wheel for GPU
      #   run: |
      #     TORBI_FAT=1 python -m build --wheel --no-isolation
      #   shell:
      #     bash

      # - name: Upload wheels as artifact
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: wheels-${{ matrix.os }}
      #     path: dist/*.whl
      #     if-no-files-found: error
      #     retention-days: 14